Traceback (most recent call last):
  File "/Users/styczynski/Code/aadg-genomics-class/presentation/robustExternalize/robExt-AEFCD574F3935EA0A1129291A9643A72.tex", line 108, in <module>
    ax.bar(x + offset, vals_index_target, width, bttom=vals_index_query,  color="#107AB0", label=f"{program_label_mapping[program_label]}: Index target")
  File "/Users/styczynski/.pyenv/versions/3.10.7/lib/python3.10/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/styczynski/.pyenv/versions/3.10.7/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 2488, in bar
    r._internal_update(kwargs)
  File "/Users/styczynski/.pyenv/versions/3.10.7/lib/python3.10/site-packages/matplotlib/artist.py", line 1223, in _internal_update
    return self._update_props(
  File "/Users/styczynski/.pyenv/versions/3.10.7/lib/python3.10/site-packages/matplotlib/artist.py", line 1197, in _update_props
    raise AttributeError(
AttributeError: Rectangle.set() got an unexpected keyword argument 'bttom'
